version: '3.3'

services:

  prometheus:
    image: lastseenvpn/monitoring:prometheus-${TAG}
    user: root
    volumes:
      - /var/lib/prometheus:/prometheus/data
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
    restart: unless-stopped
    networks:
      monitoring:
        ipv4_address: 172.28.0.11

  grafana:
    image: lastseenvpn/monitoring:grafana-${TAG}
    user: root
    depends_on:
      - prometheus
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - /var/lib/grafana:/var/lib/grafana
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
    networks:
      monitoring:
        ipv4_address: 172.28.0.10

networks:
  monitoring:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.1/24 #172.28.0.1 - 172.28.0.15

