ARG prometheus_version=v2.40.7


FROM prom/prometheus:${prometheus_version}
WORKDIR /prometheus
USER root
COPY . /etc/prometheus/
RUN mkdir -p /prometheus/data && chown -R nobody:nobody /prometheus && \
    chmod 777 /etc/prometheus/test-prometheus.sh
VOLUME [ "/prometheus/data", "/etc/prometheus" ]
CMD [ "--config.file=/etc/prometheus/prometheus.yml", \
      "--storage.tsdb.path=/prometheus", \
      "--web.console.libraries=/usr/share/prometheus/console_libraries", \
      "--web.console.templates=/usr/share/prometheus/consoles" ]
