ARG grafana_version=grafana/grafana:9.4.3

FROM ${grafana_version}
USER root
RUN apk add --no-cache shadow
COPY grafana.ini /etc/grafana/grafana.ini
COPY test-grafana.sh /etc/grafana/test-grafana.sh
RUN chmod 755 /etc/grafana/grafana.ini && \
    chmod 777 /var/lib/grafana && \
    chmod 777 /etc/grafana && \
    chmod 777 /etc/grafana/test-grafana.sh
VOLUME [ "/var/lib/grafana" ]

EXPOSE 3000

CMD ["grafana-server", "--config=/etc/grafana/grafana.ini"]
