name: Build, Test, and Push Docker Images

on:
  push:
    branches:
      - master
      - test
jobs:
  build-test-push:
    runs-on: ubuntu-20.04
    services:
      docker:
        image: docker:dind
        ports:
          - 2376/tcp
        options: >-
          --privileged
          --mount type=bind,source=/var/lib/docker,target=/var/lib/docker
          --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock
    steps:
    - name: Set commit hash
      run: | 
        echo "TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Check for changes
      run: |
        git fetch --prune
        CHANGED_FILES_graf=$(git diff --name-only HEAD~1 -- grafana/)
        echo "CHANGED_FILES_graf=$CHANGED_FILES_graf" >> $GITHUB_ENV
        echo "any_changes_graf=$(echo $CHANGED_FILES_graf | grep -E '^grafana/' | wc -l)" >> $GITHUB_ENV
        CHANGED_FILES_prom=$(git diff --name-only HEAD~1 -- prometheus/)
        echo "CHANGED_FILES_prom=$CHANGED_FILES_prom" >> $GITHUB_ENV
        echo "any_changes_prom=$(echo $CHANGED_FILES_prom | grep -E '^prometheus/' | wc -l)" >> $GITHUB_ENV

    - name: Build-test-grafana
      if: ${{ env.any_changes_graf >= 1 }}
      run: |
        echo "Start building"
        docker build -t ${{ secrets.DOCKER_USERNAME }}/grafana:$TAG grafana/
        docker run -d -p 3000:3000 --name grafana ${{ secrets.DOCKER_USERNAME }}/grafana:${{ env.TAG }}
        echo "Testing image"
        docker exec grafana /bin/bash /etc/grafana/test-grafana.sh 

    - name: Build-test-prometheus
      if: ${{ env.any_changes_prom >= 1 }}
      run: |
        echo "Start building"
        docker build -t ${{ secrets.DOCKER_USERNAME }}/prometheus:$TAG prometheus/
        docker run -d -p 9090:9090 --name prometheus ${{ secrets.DOCKER_USERNAME }}/prometheus:${{ env.TAG }}
        echo "Testing image"  
        docker exec prometheus /bin/sh /etc/prometheus/test-prometheus.sh
      
    - name: LoginDockerHub
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push-grafana
      if: ${{ env.any_changes_graf >= 1 }}
      run: |
        echo "Pushing image!"
        docker push ${{ secrets.DOCKER_USERNAME }}/grafana:${{ env.TAG }}
        docker image tag ${{ secrets.DOCKER_USERNAME }}/grafana:${{ env.TAG }} ${{ secrets.DOCKER_USERNAME }}/grafana:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/grafana:latest

    - name: Push-prometheus
      if: ${{ env.any_changes_prom >= 1 }}
      run: |
        echo "Pushing image!"
        docker push ${{ secrets.DOCKER_USERNAME }}/prometheus:${{ env.TAG }}
        docker image tag ${{ secrets.DOCKER_USERNAME }}/prometheus:${{ env.TAG }} ${{ secrets.DOCKER_USERNAME }}/prometheus:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/prometheus:latest
 
    - name: Do-nothing
      if: ${{ steps.grafana_changes.outputs.any_changes_graf == '0' && steps.prometheus_changes.outputs.any_changes_prom == '0' }}
      run: |
        echo "No changes found"
  
  deploy:
    runs-on: ubuntu-20.04
    needs: build-test-push
    steps:
      - name: Deploy 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH }} 
          port: ${{ secrets.PORT }}
          script: |
            cd /etc/monitoring && docker-compose kill;
            docker rm $(docker ps -q);
            docker system prune -a;
            docker-compose pull;
            docker-compose up -d;
            exit
