name: Build, Test, and Push Docker Images

on:
  push:
    branches:
      - test_deploy

jobs:
  build-test-push:
    runs-on: ubuntu-20.04
    outputs:
      image1: ${{ steps.Build-test-grafana.outputs.image }} 
      image2: ${{ steps.Build-test-prometheus.outputs.image }}
    services:
      docker:
        image: docker:dind
        ports:
          - 2376/tcp
        options: >-
          --privileged
          --mount type=bind,source=/var/lib/docker,target=/var/lib/docker
          --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock
        env:
          DOCKER_TLS_CERTDIR: "/etc/docker/certs.d/pupaandlupa.space/"
    steps:
    - name: Set commit hash
      run: | 
        echo "TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Check for changes
      id: changes
      run: |
        git fetch --prune
        CHANGED_FILES_graf=$(git diff --name-only HEAD~1 -- grafana/)
        echo "CHANGED_FILES_graf=$CHANGED_FILES_graf" >> $GITHUB_ENV
        echo "any_changes_graf=$(echo $CHANGED_FILES_graf | grep -E '^grafana/' | wc -l)" >> $GITHUB_ENV
        CHANGED_FILES_prom=$(git diff --name-only HEAD~1 -- prometheus/)
        echo "CHANGED_FILES_prom=$CHANGED_FILES_prom" >> $GITHUB_ENV
        echo "any_changes_prom=$(echo $CHANGED_FILES_prom | grep -E '^prometheus/' | wc -l)" >> $GITHUB_ENV

    - name: Build-test-grafana
      if: ${{ env.any_changes_graf >= 1 }}
      run: |
        echo "Start building"
        docker build -t ${{ secrets.DOCKER_USERNAME }}/grafana:$TAG grafana/
        docker run -d -p 3000:3000 --name grafana ${{ secrets.DOCKER_USERNAME }}/grafana:${{ env.TAG }}
        echo "Testing image"
        docker exec grafana /bin/bash /etc/grafana/test-grafana.sh 
        echo "name=grafana:${{ env.TAG }}" >> $GITHUB_ENV

    - name: Build-test-prometheus
      if: ${{ env.any_changes_prom >= 1 }}
      run: |
        echo "Start building"
        docker build -t ${{ secrets.DOCKER_USERNAME }}/prometheus:$TAG prometheus/
        docker run -d -p 9090:9090 --name prometheus ${{ secrets.DOCKER_USERNAME }}/prometheus:${{ env.TAG }}
        echo "Testing image"  
        docker exec prometheus /bin/sh /etc/prometheus/test-prometheus.sh
        echo "name=prometheus:${{ env.TAG }}" >> $GITHUB_ENV
      
    - name: LoginDockerHub
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tls: ${{ secrets.DOCKER_TLS_VERIFY }}
        cert: ${{ secrets.DOCKER_CERT }}
        key: ${{ secrets.DOCKER_KEY }}
        ca: ${{ secrets.DOCKER_CA }}

    - name: Push-grafana
      if: ${{ env.any_changes_graf >= 1 }}
      run: |
        echo "Pushing image!"
        docker push ${{ secrets.DOCKER_USERNAME }}/grafana:${{ env.TAG }}

    - name: Push-prometheus
      if: ${{ env.any_changes_prom >= 1 }}
      run: |
        echo "Pushing image!"
        docker push ${{ secrets.DOCKER_USERNAME }}/prometheus:${{ env.TAG }}
 
    - name: Do-nothing
      if: ${{ steps.grafana_changes.outputs.any_changes_graf == '0' && steps.prometheus_changes.outputs.any_changes_prom == '0' }}
      run: |
        echo "No changes found"

